add_newline = true

scan_timeout = 3000
command_timeout = 5000


[hostname]
ssh_symbol = "ssh[->](bold white)"

[localip]
disabled = false
ssh_only = false

[os]
disabled = false

[username]
show_always = true

[status]
disabled = false

[sudo]
disabled = false

[time]
disabled = false
